import { CrewCardProps } from "@/components/crew/card";


export const crew: CrewCardProps[] = [
  {
    gender: "male",
    name: "Bruno Cardoso",
    role: "parent",
    side: "his",
    photoUrl: "/crew/bruno.jpg",
    instagramUsername: "brunocardoso.bc",
    about: "Muito confundido como irmão do Tiago.",
  },
  {
    gender: "female",
    name: "Karine Kerber",
    role: "parent",
    side: "his",
    photoUrl: "/crew/karine.jpg",
    instagramUsername: "karinecakerber",
    about: "A novinha!",
  },
  {
    gender: "male",
    name: "Josenildo Souza",
    role: "parent",
    side: "her",
    photoUrl: "/crew/jo.png",
    instagramUsername: "",
    about: "Cabra macho!",
  },
  {
    gender: "female",
    name: "Patrícia Domingos",
    role: "parent",
    side: "her",
    photoUrl: "/crew/patricia.jpg",
    instagramUsername: "patriciadcss",
    about: "Glamurosa!",
  },
  {
    gender: "male",
    name: "Antônio Carlos Pedrosa",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/ac.png",
    instagramUsername: "",
    about: "Rei do gado e avô do Tiago.",
  },
  {
    gender: "female",
    name: "Dalva Cardoso",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/dalva.png",
    instagramUsername: "mdalvacardoso",
    about: "Lady Dalva e avó do Tiago.",
  },
  {
    gender: "male",
    name: "Alison Bessa",
    role: "padrinho",
    side: "his",
    photoUrl: "https://github.com/alisonbessa.png",
    instagramUsername: "alisonbessa",
    about: "Primeiro chefe do Tiago, parceiro de JiuJitsu e grande amigo.",
  },
  {
    gender: "female",
    name: "Érika Barros",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/erika.jpg",
    instagramUsername: "erikaabarrros",
    about: "Kinha sunshine alto astral!",
  },
  {
    gender: "male",
    name: "Pedro Silva",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/pedro.png",
    instagramUsername: "",
    about: "Mais conhecido como Pedro da Manga, avô da Thaís",
  },
  {
    gender: "female",
    name: "Risomar Domingos",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/risomar.png",
    instagramUsername: "",
    about: "Federal e avó da Thaís",
  },
  {
    gender: "male",
    name: "Wesley Furtado",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/wesley.jpg",
    instagramUsername: "wesleyfurtado5",
    about: "Um dos grandes amigos de João Pessoa da Thaís.",
  },
  {
    gender: "female",
    name: "Juliana Nunes",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/juliana.jpg",
    instagramUsername: "juliananunesc_",
    about: "Uma das grandes amigas de João Pessoa da Thaís.",
  },
]