import { CrewCardProps } from "@/components/crew/card";


export const crew: CrewCardProps[] = [
  {
    gender: "male",
    name: "Bruno Cardoso",
    role: "parent",
    side: "his",
    photoUrl: "/crew/bruno.jpg",
    instagramUsername: "brunocardoso.bc",
    about: "O pai babão, entusiasta de tecnologias e frequentemente confundido como irmão do Tiago, provando que a juventude está no coração, não no RG.",
  },
  {
    gender: "female",
    name: "Karine Kerber",
    role: "parent",
    side: "his",
    photoUrl: "/crew/karine.jpg",
    instagramUsername: "karinecakerber",
    about: "Mãezona, bailarina animadora da pista de dança e a novinha que nos ensina que a idade é só um detalhe quando se trata de aproveitar a vida.",
  },
  {
    gender: "male",
    name: "Josenildo Souza",
    role: "parent",
    side: "her",
    photoUrl: "/crew/jo.png",
    instagramUsername: "",
    about: "Cabra Macho, pai pra toda obra, também conhecido como Nildo.",
  },
  {
    gender: "female",
    name: "Patrícia Domingos",
    role: "parent",
    side: "her",
    photoUrl: "/crew/patricia.jpg",
    instagramUsername: "patriciadcss",
    about: "Patty, Mãe leoa, eternamente jovem, com uma risada icônica que faz cada momento mais leve e divertido.",
  },
  {
    gender: "male",
    name: "Antônio Carlos Pedrosa",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/ac.png",
    instagramUsername: "",
    about: "Rei do gado e avô do Tiago.",
  },
  {
    gender: "female",
    name: "Dalva Cardoso",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/dalva.png",
    instagramUsername: "mdalvacardoso",
    about: "Lady Dalva e avó do Tiago.",
  },
  {
    gender: "male",
    name: "Alison Bessa",
    role: "padrinho",
    side: "his",
    photoUrl: "https://github.com/alisonbessa.png",
    instagramUsername: "alisonbessa",
    about: "Primeiro chefe do Tiago, parceiro de JiuJitsu e grande amigo.",
  },
  {
    gender: "female",
    name: "Érika Barros",
    role: "padrinho",
    side: "his",
    photoUrl: "/crew/erika.jpg",
    instagramUsername: "erikaabarrros",
    about: "Kinha sunshine alto astral!",
  },
  {
    gender: "male",
    name: "Pedro Silva",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/pedro.png",
    instagramUsername: "",
    about: "A noiva é a sua fofinha, mais conhecido como Pedro da Manga, o avô da noiva.",
  },
  {
    gender: "female",
    name: "Risomar Domingos",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/risomar.png",
    instagramUsername: "",
    about: "Federal, onde a noiva é seu rubi, mais conhecida carinhosamente como Sorriso, a maga dos momentos icônicos na família Castro, avó da noiva.",
  },
  {
    gender: "male",
    name: "Wesley Furtado",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/wesley.jpg",
    instagramUsername: "wesleyfurtado5",
    about: "Companheiro de risadas e detentor do título de 'Melhor mediador de conflitos', é o grande amigo da noiva que torna cada desafio mais leve com seu bom humor contagiante.",
  },
  {
    gender: "female",
    name: "Juliana Nunes",
    role: "padrinho",
    side: "her",
    photoUrl: "/crew/juliana.jpg",
    instagramUsername: "juliananunesc_",
    about: "Grande amiga da noiva, que considera a noiva como seu smurf. Também conhecida como avatar (pela noiva) - a parceira perfeita para aventuras e risadas.",
  },
]